name: Deploy
on:
  workflow_call:
    SLACK_WEBHOOK_URL:
      required: true
permissions:
  id-token: write
  contents: read 
  deployments: write
jobs:
  deploy:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        channel: '#deployment'
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_SLACK_WEBHOOK_URL }} # required
      if: always()
